"""Which field paths an answers document may use, and which form version they are.

The Protokoll's fields exist nowhere but inside the legacy PDF. They were read
out of it once by scripts/extract_form_definition.py into
database/seed/form_version_20260609/felder.json, and that file is what this
module publishes.

Read rather than retyped, and this is the whole point of the module. Five
hundred and forty dotted paths written out again by hand is five hundred and
forty chances at a typo that nothing would catch, and the frontend already
builds its own fields from this same file. One source means the two halves
cannot drift apart without the tests noticing.

project-overview.md puts this in a FormVersion table eventually, one row per
version, locked by ADR 0004 so that a historical protocol stays renderable
forever. That table is feature 11's, because feature 11 is the first thing that
needs the stored rules rather than only the names. Until then these are plain
files and there is exactly one version.
"""

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

from app.config import get_settings

FELDER_DATEI = "felder.json"

# What the app asks for that the printed form has no field for.
#
# Listed here rather than waved through by a loose rule, so the things we added
# on top of the legacy form stay countable. Every entry needs a reason and a
# question on the record, because an addition is a place where our document and
# FiaKa's expectations differ.
#
# bearbeiter.ort: the PDF has a street and a postcode but no town, which both the
# mockup and the Person model have. Added in feature 4b; question 1 in
# docs/ffs-questions.md.
ZUSAETZLICHE_PFADE = frozenset({"bearbeiter.ort"})


class FormularDefinitionFehlt(RuntimeError):
    """The seed the backend was built to read is not where it should be.

    A broken image or a broken checkout rather than anything a user did, so it
    fails at startup with the path it looked at. The alternative is a service
    that starts happily and refuses every save later, with a message about field
    paths that sends whoever reads it looking in entirely the wrong place.
    """

    def __init__(self, pfad: Path, grund: str) -> None:
        super().__init__(
            f"The form definition could not be read from {pfad}: {grund}."
            " It is generated by backend/scripts/extract_form_definition.py and"
            " lives in database/seed/. Set FORMULAR_SEED_DIR if it is somewhere"
            " else in this deployment."
        )


@dataclass(frozen=True)
class FormularDefinition:
    """One form version's field list."""

    version: str
    #: Every path an answers document may carry, the additions above included.
    pfade: frozenset[str]


def lade(verzeichnis: Path) -> FormularDefinition:
    """Read one version's field list out of its seed directory.

    Takes the directory rather than reading the configured one, so the failure
    cases below are testable without a broken checkout.

    The count in the file is checked against the list beside it. Both are written
    by the same generator, so disagreement means the file was edited by hand or
    truncated in transit, and a silently short field list would show up much later
    as a valid protocol being refused.
    """
    pfad = verzeichnis / FELDER_DATEI

    try:
        roh = json.loads(pfad.read_text(encoding="utf-8"))
    except OSError as fehler:
        raise FormularDefinitionFehlt(pfad, "it could not be opened") from fehler
    except json.JSONDecodeError as fehler:
        raise FormularDefinitionFehlt(pfad, "it is not readable JSON") from fehler

    if not isinstance(roh, dict):
        raise FormularDefinitionFehlt(pfad, "its top level is not an object")

    version = roh.get("version")
    felder = roh.get("felder")
    anzahl = roh.get("anzahl")
    if not isinstance(version, str) or not isinstance(felder, list):
        raise FormularDefinitionFehlt(pfad, "it has no version or no field list")

    namen = frozenset(
        feld["name"]
        for feld in felder
        if isinstance(feld, dict) and isinstance(feld.get("name"), str)
    )
    if len(namen) != len(felder) or len(namen) != anzahl:
        raise FormularDefinitionFehlt(
            pfad, f"it claims {anzahl} fields and holds {len(namen)} distinct usable names"
        )

    return FormularDefinition(version=version, pfade=namen | ZUSAETZLICHE_PFADE)


@lru_cache
def formular() -> FormularDefinition:
    """The form version this deployment serves, read once per process.

    Cached because the file cannot change while the service runs, and because the
    shape check consults it on every save.

    There is one version, so the configured directory names it and the version
    string itself is only ever read back out of the file. Feature 11 is where
    several versions coexist and this becomes a lookup.
    """
    return lade(get_settings().formular_seed_dir)
