"""Which field paths an answers document may use, and which form version they are.

The Protokoll's fields exist nowhere but inside the legacy PDF. They were read
out of it once by scripts/extract_form_definition.py into
database/seed/form_version_20260609/felder.json, and that file is what this
module publishes.

Read rather than retyped, and this is the whole point of the module. Five
hundred and forty dotted paths written out again by hand is five hundred and
forty chances at a typo that nothing would catch, and the frontend already
builds its own fields from this same file. One source means the two halves
cannot drift apart without the tests noticing.

project-overview.md puts this in a FormVersion table eventually, one row per
version, locked by ADR 0004 so that a historical protocol stays renderable
forever. That table is feature 11's, because feature 11 is the first thing that
needs the stored rules rather than only the names. Until then these are plain
files and there is exactly one version.
"""

import json
from dataclasses import dataclass, field
from enum import IntEnum, StrEnum
from functools import lru_cache
from pathlib import Path
from typing import Any

from app.config import get_settings

FELDER_DATEI = "felder.json"

# What the app asks for that the printed form has no field for.
#
# Listed here rather than waved through by a loose rule, so the things we added
# on top of the legacy form stay countable. Every entry needs a reason and a
# question on the record, because an addition is a place where our document and
# FiaKa's expectations differ.
#
# bearbeiter.ort: the PDF has a street and a postcode but no town, which both the
# mockup and the Person model have. Added in feature 4b; question 1 in
# docs/ffs-questions.md.
ZUSAETZLICHE_PFADE = frozenset({"bearbeiter.ort"})


class FormularDefinitionFehlt(RuntimeError):
    """The seed the backend was built to read is not where it should be.

    A broken image or a broken checkout rather than anything a user did, so it
    fails at startup with the path it looked at. The alternative is a service
    that starts happily and refuses every save later, with a message about field
    paths that sends whoever reads it looking in entirely the wrong place.
    """

    def __init__(self, pfad: Path, grund: str) -> None:
        super().__init__(
            f"The form definition could not be read from {pfad}: {grund}."
            " It is generated by backend/scripts/extract_form_definition.py and"
            " lives in database/seed/. Set FORMULAR_SEED_DIR if it is somewhere"
            " else in this deployment."
        )


class Formatart(StrEnum):
    """The three ways this form writes a value that is not plain text."""

    #: A date, by a pattern the form declares. Always dd.mm.yyyy in this version.
    DATUM = "datum"
    #: A time as HH:MM, which is already how the application stores one.
    ZEIT = "zeit"
    #: A number, with decimal places and a separator style.
    ZAHL = "zahl"


class Trennung(IntEnum):
    """Acrobat's four ways of punctuating a number, as its own numbers 0 to 3.

    An enum rather than a bare int so that the two separators are read off the
    style itself instead of from a pair of lookup tables somewhere else, and so
    that a style this application has never heard of is refused where the seed is
    read rather than quietly treated as one of these four. Getting that wrong is
    not a crash: it is a catch of 1234 fish stored as 1.2.
    """

    #: 1,234.56 - the American one. One field in this form uses it.
    KOMMA_GRUPPIERT = 0
    #: 1234.56 - no grouping, dot decimals. The four stocking years.
    PUNKT_DEZIMAL = 1
    #: 1.234,56 - the German one, and 373 of this form's 383 numbers.
    PUNKT_GRUPPIERT = 2
    #: 1234,56 - no grouping, comma decimals. The coordinates and one Schätzwert.
    KOMMA_DEZIMAL = 3

    @property
    def gruppentrenner(self) -> str:
        """What separates the thousands, or nothing where this style groups none.

        Where it is empty, a dot in the value can only ever be a decimal point,
        which is what makes those two styles the safe ones.
        """
        return {Trennung.KOMMA_GRUPPIERT: ",", Trennung.PUNKT_GRUPPIERT: "."}.get(self, "")

    @property
    def dezimaltrenner(self) -> str:
        """What marks the decimals."""
        return "," if self in (Trennung.PUNKT_GRUPPIERT, Trennung.KOMMA_DEZIMAL) else "."


@dataclass(frozen=True, slots=True)
class Feldformat:
    """How one field writes its value, as the extraction script read it.

    Only the parts that decide what a value means. Acrobat's number format also
    carries a currency and a style for negatives, and neither changes which
    digits the value has.
    """

    art: Formatart
    #: Decimal places. Numbers only, and never more than one in this form.
    stellen: int = 0
    #: How the number is punctuated. Numbers only.
    trennung: Trennung = Trennung.KOMMA_GRUPPIERT
    #: The declared date pattern. Dates only.
    muster: str = ""


@dataclass(frozen=True)
class FormularDefinition:
    """One form version's field list."""

    version: str
    #: Every path an answers document may carry, the additions above included.
    pfade: frozenset[str]
    #: How a field writes its value, for the 385 that do not write plain text.
    #: Read by the PDF import, which is the only thing that meets a value written
    #: the form's way rather than ours.
    formate: dict[str, Feldformat] = field(default_factory=dict)


def lade(verzeichnis: Path) -> FormularDefinition:
    """Read one version's field list out of its seed directory.

    Takes the directory rather than reading the configured one, so the failure
    cases below are testable without a broken checkout.

    The count in the file is checked against the list beside it. Both are written
    by the same generator, so disagreement means the file was edited by hand or
    truncated in transit, and a silently short field list would show up much later
    as a valid protocol being refused.
    """
    pfad = verzeichnis / FELDER_DATEI

    try:
        roh = json.loads(pfad.read_text(encoding="utf-8"))
    except OSError as fehler:
        raise FormularDefinitionFehlt(pfad, "it could not be opened") from fehler
    except json.JSONDecodeError as fehler:
        raise FormularDefinitionFehlt(pfad, "it is not readable JSON") from fehler

    if not isinstance(roh, dict):
        raise FormularDefinitionFehlt(pfad, "its top level is not an object")

    version = roh.get("version")
    felder = roh.get("felder")
    anzahl = roh.get("anzahl")
    if not isinstance(version, str) or not isinstance(felder, list):
        raise FormularDefinitionFehlt(pfad, "it has no version or no field list")

    namen = frozenset(
        feld["name"]
        for feld in felder
        if isinstance(feld, dict) and isinstance(feld.get("name"), str)
    )
    if len(namen) != len(felder) or len(namen) != anzahl:
        raise FormularDefinitionFehlt(
            pfad, f"it claims {anzahl} fields and holds {len(namen)} distinct usable names"
        )

    return FormularDefinition(
        version=version,
        pfade=namen | ZUSAETZLICHE_PFADE,
        formate=_formate(pfad, felder),
    )


def _formate(pfad: Path, felder: list[Any]) -> dict[str, Feldformat]:
    """How each field writes its value, for the ones that declare it.

    Generated alongside the names by the same script, so a malformed entry here
    means the file was hand-edited or truncated. That fails at startup with the
    path, like every other problem with this file, rather than surfacing later as
    an imported date in the wrong order.
    """
    formate: dict[str, Feldformat] = {}
    for feld in felder:
        roh = feld.get("format") if isinstance(feld, dict) else None
        if roh is None:
            continue
        try:
            formate[feld["name"]] = Feldformat(
                art=Formatart(roh["art"]),
                stellen=int(roh.get("stellen", 0)),
                trennung=Trennung(int(roh.get("trennung", 0))),
                muster=str(roh.get("muster", "")),
            )
        except (KeyError, TypeError, ValueError) as fehler:
            raise FormularDefinitionFehlt(
                pfad, f"the format of {feld.get('name')!r} is not readable"
            ) from fehler
    return formate


@lru_cache
def formular() -> FormularDefinition:
    """The form version this deployment serves, read once per process.

    Cached because the file cannot change while the service runs, and because the
    shape check consults it on every save.

    There is one version, so the configured directory names it and the version
    string itself is only ever read back out of the file. Feature 11 is where
    several versions coexist and this becomes a lookup.
    """
    return lade(get_settings().formular_seed_dir)
