"""artcodes index

The index behind the review queue's species filter, feature 12c.

It covers the species codes of a protocol's catch table, collected out of the
answers document by jsonb_path_query_array over $.arten.*.name. Without it,
asking which protocols caught a Hecht reads every submission end to end, because
the codes are inside a JSON document rather than in a column of their own.

jsonb_path_ops rather than the default jsonb_ops: it is the operator class built
for the @> containment the query uses, and the smaller of the two, since the
extracted value is an array of codes with no keys for the default class to index.

**The expression is written out here rather than imported from
app/models/protokoll.py**, which is the same rule the workflow-events migration
above states: a migration records what the database was changed to on one day,
while the model keeps moving afterwards, so a migration reaching into app/ starts
failing the moment somebody edits a class it mentions. The model declares the
same index so a reader of the table sees it; the two are kept the same by hand,
and the tests are what would notice.

Not CREATE INDEX CONCURRENTLY. Alembic runs a migration inside a transaction and
CONCURRENTLY cannot run in one. Building it plainly takes a write lock on
submissions for as long as the build takes, which on a table this size is a
moment, and applying migrations is already a deploy step somebody runs rather
than something that happens when the service starts.

Written by hand rather than autogenerated. Alembic does not reflect
expression-based indexes, so autogenerate neither writes this one nor notices it
is missing.

Revision ID: 23a161edb386
Revises: 280292a056d8
Create Date: 2026-09-18 11:45:29.859747

"""

from collections.abc import Sequence

from alembic import op

revision: str = "23a161edb386"
down_revision: str | Sequence[str] | None = "280292a056d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

INDEX = "ix_submissions_artcodes"

# The literal jsonpath, not a parameter. Postgres decides whether an expression
# index applies by comparing expression trees, so the query has to arrive at the
# planner spelling this the same way the index does.
AUSDRUCK = "jsonb_path_query_array(antworten, CAST('$.arten.*.name' AS JSONPATH))"


def upgrade() -> None:
    op.execute(f"CREATE INDEX {INDEX} ON submissions USING gin (({AUSDRUCK}) jsonb_path_ops)")


def downgrade() -> None:
    op.execute(f"DROP INDEX {INDEX}")
